//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debianet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Debianet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Press &lt;space&gt; to select, &lt;enter&gt; to accept, &lt;esc&gt; to cancel).
        /// </summary>
        internal static string App_MultiSelectionInstructions {
            get {
                return ResourceManager.GetString("App_MultiSelectionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string DotnetMenu_Item_Back {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all local NuGet caches....
        /// </summary>
        internal static string DotnetMenu_Item_ClearNugetCache {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ClearNugetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET runtimes....
        /// </summary>
        internal static string DotnetMenu_Item_ListRuntimes {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET SDKs....
        /// </summary>
        internal static string DotnetMenu_Item_ListSdks {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListSdks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed global tools....
        /// </summary>
        internal static string DotnetMenu_Item_ListTools {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET workloads....
        /// </summary>
        internal static string DotnetMenu_Item_ListWorkloads {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed global tools....
        /// </summary>
        internal static string DotnetMenu_Item_UpdateTools {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_UpdateTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed workloads....
        /// </summary>
        internal static string DotnetMenu_Item_UpdateWorkloads {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_UpdateWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET commands.
        /// </summary>
        internal static string DotnetMenu_Title {
            get {
                return ResourceManager.GetString("DotnetMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET tool installer.
        /// </summary>
        internal static string DotnetToolsInstall_Title {
            get {
                return ResourceManager.GetString("DotnetToolsInstall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .NET Tools....
        /// </summary>
        internal static string MainMenu_DotnetToolsInstall {
            get {
                return ResourceManager.GetString("MainMenu_DotnetToolsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET related commands....
        /// </summary>
        internal static string MainMenu_Item_Dotnet {
            get {
                return ResourceManager.GetString("MainMenu_Item_Dotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainMenu_Item_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Item_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debianet main menu.
        /// </summary>
        internal static string MainMenu_Title {
            get {
                return ResourceManager.GetString("MainMenu_Title", resourceCulture);
            }
        }
    }
}
