//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debianet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Debianet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Press &lt;space&gt; to select, &lt;enter&gt; to accept, &lt;esc&gt; to cancel).
        /// </summary>
        internal static string App_MultiSelectionInstructions {
            get {
                return ResourceManager.GetString("App_MultiSelectionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string Dialog_Sysinfo {
            get {
                return ResourceManager.GetString("Dialog_Sysinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker.
        /// </summary>
        internal static string DockerMenu_Title {
            get {
                return ResourceManager.GetString("DockerMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all local NuGet caches....
        /// </summary>
        internal static string DotnetMenu_Item_ClearNugetCache {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ClearNugetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET runtimes....
        /// </summary>
        internal static string DotnetMenu_Item_ListRuntimes {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET SDKs....
        /// </summary>
        internal static string DotnetMenu_Item_ListSdks {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListSdks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed global tools....
        /// </summary>
        internal static string DotnetMenu_Item_ListTools {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET workloads....
        /// </summary>
        internal static string DotnetMenu_Item_ListWorkloads {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_ListWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed global tools....
        /// </summary>
        internal static string DotnetMenu_Item_UpdateTools {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_UpdateTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed workloads....
        /// </summary>
        internal static string DotnetMenu_Item_UpdateWorkloads {
            get {
                return ResourceManager.GetString("DotnetMenu_Item_UpdateWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET commands.
        /// </summary>
        internal static string DotnetMenu_Title {
            get {
                return ResourceManager.GetString("DotnetMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET tool installer.
        /// </summary>
        internal static string DotnetToolsInstall_Title {
            get {
                return ResourceManager.GetString("DotnetToolsInstall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changelog....
        /// </summary>
        internal static string MainMenu_Changelog {
            get {
                return ResourceManager.GetString("MainMenu_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker....
        /// </summary>
        internal static string MainMenu_Docker {
            get {
                return ResourceManager.GetString("MainMenu_Docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .NET Tools....
        /// </summary>
        internal static string MainMenu_DotnetToolsInstall {
            get {
                return ResourceManager.GetString("MainMenu_DotnetToolsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET related commands....
        /// </summary>
        internal static string MainMenu_Item_Dotnet {
            get {
                return ResourceManager.GetString("MainMenu_Item_Dotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainMenu_Item_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Item_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System....
        /// </summary>
        internal static string MainMenu_System {
            get {
                return ResourceManager.GetString("MainMenu_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info....
        /// </summary>
        internal static string MainMenu_SystemInfo {
            get {
                return ResourceManager.GetString("MainMenu_SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debianet main menu.
        /// </summary>
        internal static string MainMenu_Title {
            get {
                return ResourceManager.GetString("MainMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        internal static string Menu_Item_Back {
            get {
                return ResourceManager.GetString("Menu_Item_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is only supported on Linux systems..
        /// </summary>
        internal static string StartupCheck_NotLinux {
            get {
                return ResourceManager.GetString("StartupCheck_NotLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the application as a normal user..
        /// </summary>
        internal static string StartupCheck_RootUser {
            get {
                return ResourceManager.GetString("StartupCheck_RootUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string SysInfo_Cpu {
            get {
                return ResourceManager.GetString("SysInfo_Cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disks.
        /// </summary>
        internal static string SysInfo_Disks {
            get {
                return ResourceManager.GetString("SysInfo_Disks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name.
        /// </summary>
        internal static string SysInfo_HostName {
            get {
                return ResourceManager.GetString("SysInfo_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version.
        /// </summary>
        internal static string SysInfo_KernelVersion {
            get {
                return ResourceManager.GetString("SysInfo_KernelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string SysInfo_Memory {
            get {
                return ResourceManager.GetString("SysInfo_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        internal static string SysInfo_Shell {
            get {
                return ResourceManager.GetString("SysInfo.Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        internal static string SysInfo_Uptime {
            get {
                return ResourceManager.GetString("SysInfo_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean apt cache....
        /// </summary>
        internal static string SystemMenu_AptClean {
            get {
                return ResourceManager.GetString("SystemMenu_AptClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install c/c++ dev tools.
        /// </summary>
        internal static string SystemMenu_InstallCpp {
            get {
                return ResourceManager.GetString("SystemMenu_InstallCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemMenu_Title {
            get {
                return ResourceManager.GetString("SystemMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System update....
        /// </summary>
        internal static string SystemMenu_Update {
            get {
                return ResourceManager.GetString("SystemMenu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string TextView_Changelog {
            get {
                return ResourceManager.GetString("TextView_Changelog", resourceCulture);
            }
        }
    }
}
