//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebiaNetApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebiaNetApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is only supported on Linux systems..
        /// </summary>
        public static string Error_NotLinux {
            get {
                return ResourceManager.GetString("Error_NotLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the application as a normal user..
        /// </summary>
        public static string Error_SudoUser {
            get {
                return ResourceManager.GetString("Error_SudoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command:.
        /// </summary>
        public static string Info_Executing {
            get {
                return ResourceManager.GetString("Info_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process exit code:.
        /// </summary>
        public static string Info_ExitCode {
            get {
                return ResourceManager.GetString("Info_ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command  finished. Total runtime in seconds:.
        /// </summary>
        public static string Info_Runtime {
            get {
                return ResourceManager.GetString("Info_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear NuGet caches.
        /// </summary>
        public static string Menu_ClearNugetCache {
            get {
                return ResourceManager.GetString("Menu_ClearNugetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Distribution.
        /// </summary>
        public static string Menu_DistUpgrade {
            get {
                return ResourceManager.GetString("Menu_DistUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all containers.
        /// </summary>
        public static string Menu_Docker_ListAllContainers {
            get {
                return ResourceManager.GetString("Menu_Docker_ListAllContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List images.
        /// </summary>
        public static string Menu_Docker_ListImages {
            get {
                return ResourceManager.GetString("Menu_Docker_ListImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List running conainers.
        /// </summary>
        public static string Menu_Docker_ListRunningContainers {
            get {
                return ResourceManager.GetString("Menu_Docker_ListRunningContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all running containers.
        /// </summary>
        public static string Menu_Docker_Stop {
            get {
                return ResourceManager.GetString("Menu_Docker_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List globaly installed .NET Tools.
        /// </summary>
        public static string Menu_ListDotnetTools {
            get {
                return ResourceManager.GetString("Menu_ListDotnetTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET workloads.
        /// </summary>
        public static string Menu_ListDotnetWorkloads {
            get {
                return ResourceManager.GetString("Menu_ListDotnetWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List environment variables.
        /// </summary>
        public static string Menu_ListEnvironmentVariables {
            get {
                return ResourceManager.GetString("Menu_ListEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed .NET runtime &amp; SDK versions.
        /// </summary>
        public static string Menu_RuntimeAndSdks {
            get {
                return ResourceManager.GetString("Menu_RuntimeAndSdks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to docker menu....
        /// </summary>
        public static string Menu_SwitchDocker {
            get {
                return ResourceManager.GetString("Menu_SwitchDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed .NET Tools.
        /// </summary>
        public static string Menu_UpdateDotnetTools {
            get {
                return ResourceManager.GetString("Menu_UpdateDotnetTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update .NET Workloads.
        /// </summary>
        public static string Menu_UpdateDotnetWorkloads {
            get {
                return ResourceManager.GetString("Menu_UpdateDotnetWorkloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option.
        /// </summary>
        public static string Prompt_SelectAnOption {
            get {
                return ResourceManager.GetString("Prompt_SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container:.
        /// </summary>
        public static string Table_Header_Container {
            get {
                return ResourceManager.GetString("Table_Header_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Table_Header_Property {
            get {
                return ResourceManager.GetString("Table_Header_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Table_Header_Value {
            get {
                return ResourceManager.GetString("Table_Header_Value", resourceCulture);
            }
        }
    }
}
